### ISSUE TITLE
Moves objects 100x more?

### ISSUE THREAD

**Issue by nullstalgia** [JuzoVR/WorldSync#1]
Howdy, I'm adding this to my avatar, and I'm finding that the position of the constraint is multiplied?

![image](https://github.com/JuzoVR/WorldSync/assets/20761757/54da36c1-f53a-4e8e-b08e-d5cfc8d05018)

![image](https://github.com/JuzoVR/WorldSync/assets/20761757/e0b0d5fd-83a2-48e3-90cd-b484f7a3c134)

Happens when merging with VRCFury or AV3Manager.

The position of the contacts seems to be right?

![image](https://github.com/JuzoVR/WorldSync/assets/20761757/37b1f797-4ccf-4ff2-a4ad-d92be8891067)

![image](https://github.com/JuzoVR/WorldSync/assets/20761757/d9b21595-f7a0-4075-acd7-1069806df723)

Happens even if placed on a normal bone.

**Comment by JuzoVR** [comment]
Worked out with user in 1:1 previously.
